name: riverpod_persistent_state
description: Persistent store for riverpod package based on hive
version: 2.1.0
repository: https://github.com/massa-org/riverpod_persistent_state

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  hive: ^2.2.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
