name: riverpod_persistent_state
description: Persistent store for riverpod package based on hive
version: 1.0.0
repository: https://github.com/massa-org/riverpod_persistent_state

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^1.0.0
  hive: ^2.0.0
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0